'use client';

import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import {
  Cpu,
  Wifi,
  Clock,
  Satellite,
  Zap,
  Settings,
  CircuitBoard,
} from 'lucide-react';
import Image from 'next/image';
import { useState } from 'react';

const hardwareData = [
  {
    name: 'STM32',
    icon: Cpu,
    imageSrc: '/images/stm32.webp',
    description:
      'A powerful 32-bit microcontroller that serves as the system’s primary brain.',
    benefit:
      'Handles complex logic, sensor data processing, and motor control timing with high efficiency.',
  },
  {
    name: 'ESP32',
    icon: Wifi,
    imageSrc: '/images/esp32.png',
    description: 'A high-speed Wi-Fi/Bluetooth gateway.',
    benefit:
      'Allows the STM32 to send telemetry data to the cloud or receive remote commands over the internet for real-time monitoring.',
  },
  {
    name: 'DS3231',
    icon: Clock,
    imageSrc: '/images/ds3231.jpeg',
    description:
      'A highly accurate real-time clock (RTC) equipped with battery backup.',
    benefit:
      'Ensures the system always knows the exact date and time for precise astronomical calculations, even after a power loss.',
  },
  {
    name: 'NEO-7M',
    icon: Satellite,
    imageSrc: '/images/neo7m.jpg',
    description:
      'A GPS module providing exact geographic coordinates and satellite-synced time.',
    benefit:
      'Essential for dynamically calculating the sun’s exact trajectory relative to your specific physical location on Earth.',
  },
  {
    name: 'INA219',
    icon: Zap,
    imageSrc: '/images/ina219.jpg',
    description:
      'A specialized sensor monitoring high-side voltage and DC current via an I2C interface.',
    benefit:
      'Enables precise tracking of power consumption and the actual energy yield being generated by the solar panel.',
  },
  {
    name: 'NEMA 17 Motors',
    icon: Settings,
    imageSrc: '/images/nema17.png',
    description:
      'Standard bipolar stepper motors known for their high precision and holding torque.',
    benefit:
      'Allows the system to move the solar array to specific angular positions with high repeatability and stability against wind load.',
  },
  {
    name: 'DRV8825',
    icon: CircuitBoard,
    imageSrc: '/images/drv8825.jpg',
    description:
      'Motor driver modules acting as the heavy-duty bridge between the STM32 and the motors.',
    benefit:
      'Handles the high-current demands of the NEMA 17s and supports microstepping for smoother, quieter, and more precise movement.',
  },
];

export default function HardwareComponents() {
  return (
    <>
      <h3 className="text-helion-green font-grotesk font-thin text-start w-full max-w-5xl mx-auto mb-6">
        HARDWARE COMPONENTS
      </h3>

      <div className="block md:hidden">
        <HardwareMobile />
      </div>

      <div className="hidden md:block w-full">
        <HardwareDesktop />
      </div>
    </>
  );
}

function HardwareMobile() {
  return (
    <div className="w-full relative">
      {hardwareData.map((item, index) => {
        const Icon = item.icon;

        return (
          <div
            key={item.name}
            className={`bg-background py-3 sticky flex flex-col min-h-100 ${index > 0 ? 'border-t' : ''}`}
            style={{ top: `${index * 2}rem` }}
          >
            {/* Header */}
            <div className="flex items-center gap-3">
              <Icon className="size-10 stroke-helion-green" />
              <p className="text-lg font-semibold">{item.name}</p>
            </div>

            {/* Image */}
            <div className="relative h-48 w-full rounded-md overflow-hidden my-4 border bg-muted/20">
              <Image
                src={item.imageSrc}
                fill
                className="object-cover"
                alt={`${item.name} module`}
              />
            </div>

            {/* Text */}
            <div className="flex flex-col gap-3 pb-3">
              <p className="font-medium text-foreground">{item.description}</p>
              <p className="text-muted-foreground text-sm leading-relaxed">
                {/* <span className="font-semibold text-helion-green mr-1">
                  Benefit:
                </span> */}
                {item.benefit}
              </p>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function HardwareDesktop() {
  const [activeIndex, setActiveIndex] = useState(0);

  const activeItem = hardwareData[activeIndex];

  return (
    <div className="w-full max-w-5xl mx-auto flex border rounded-xl min-h-125 p-4 bg-background">
      {/* buttons */}
      <div className="flex w-full max-w-72 flex-col gap-2 pr-4 overflow-y-auto">
        {hardwareData.map((item, index) => {
          const isActive = activeIndex === index;
          const Icon = item.icon;

          return (
            <Button
              key={item.name}
              variant={isActive ? 'secondary' : 'ghost'}
              className={`h-16 justify-start px-4 transition-all ${
                isActive
                  ? 'bg-helion-green/10 text-helion-green hover:text-helion-green hover:bg-helion-green/15'
                  : 'text-muted-foreground'
              }`}
              onClick={() => setActiveIndex(index)}
            >
              <Icon
                className={`mr-3 size-5 ${isActive ? 'stroke-helion-green' : 'stroke-muted-foreground'}`}
              />
              <span className="font-semibold">{item.name}</span>
            </Button>
          );
        })}
      </div>

      <Separator orientation="vertical" className="h-auto" />

      {/* content */}
      <div className="w-full flex flex-col pl-8 py-2 relative">
        <div
          key={activeItem.name}
          className="flex flex-col h-full animate-in fade-in slide-in-from-right-4 duration-500 fill-mode-forwards"
        >
          <div className="flex items-center gap-3 mb-6">
            <activeItem.icon className="size-8 stroke-helion-green" />
            <h3 className="text-3xl font-bold tracking-tight">
              {activeItem.name}
            </h3>
          </div>

          <div className="relative h-64 w-full rounded-lg overflow-hidden mb-8 border bg-muted/20">
            <Image
              src={activeItem.imageSrc}
              fill
              className="object-cover"
              alt={`${activeItem.name} detail view`}
            />
          </div>

          <div className="flex flex-col gap-5 mt-auto">
            <p className="text-xl font-medium text-foreground leading-snug">
              {activeItem.description}
            </p>
            {/* <div className="bg-muted/30 p-4 rounded-lg border border-border/50"> */}
            <p className="text-muted-foreground leading-relaxed">
              {/* <span className="font-semibold text-helion-green tracking-wide uppercase text-sm mr-3">
                  Core Benefit
                </span> */}
              {activeItem.benefit}
            </p>
            {/* </div> */}
          </div>
        </div>
      </div>
    </div>
  );
}
